version: '3'

services:
  nodejs-app:
    # image: my-app:v0.2
    build: 
      context: nodejs-app
      # dockerfile: nodejs-app/Dockerfile
    environment:
      - PORT=1337
      - DATABASE_URL=postgres://postgres:1234@postgres-app:5432/postgres
    ports:
      - 1337:1337
    depends_on: 
      - postgres-app

  postgres-app:
    image: postgres:9.6
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432
    volumes:
      - $PWD/pg/data:/var/lib/postgresql/data
      - $PWD/pg/sockets:/var/run/postgresql/

